import {
  ArrowRight,
  BrainCircuit,
  CloudRain,
} from "lucide-react";

export default function BeforeAfter() {

  return (

    <section className="mt-8 rounded-3xl border border-slate-800 bg-slate-900/70 p-7">

      <div className="mb-6">

        <p className="text-sm font-semibold uppercase tracking-[0.2em] text-emerald-400">
          Core Problem → Core Solution
        </p>

        <h2 className="mt-2 text-2xl font-semibold">
          Before vs After GramCast AI
        </h2>

        <p className="mt-2 text-sm text-slate-400">
          A coarse block-level forecast is converted into
          localized Panchayat-level weather intelligence.
        </p>

      </div>


      <div className="grid gap-5 lg:grid-cols-[1fr_auto_1fr] lg:items-center">

        <div className="rounded-3xl border border-slate-800 bg-slate-950 p-6">

          <div className="flex items-center gap-3">

            <CloudRain className="text-blue-400" />

            <h3 className="font-semibold">
              Before
            </h3>

          </div>


          <p className="mt-5 text-sm text-slate-500">
            Block-Level Forecast
          </p>

          <p className="mt-1 text-4xl font-bold">
            20 mm
          </p>


          <div className="mt-6 grid grid-cols-2 gap-3">

            {[
              "Panchayat A",
              "Panchayat B",
              "Panchayat C",
              "Panchayat D",
            ].map((name) => (

              <div
                key={name}
                className="rounded-xl border border-slate-800 bg-slate-900 p-3"
              >

                <p className="text-xs text-slate-500">
                  {name}
                </p>

                <p className="mt-1 font-semibold">
                  20 mm
                </p>

              </div>

            ))}

          </div>

        </div>


        <div className="hidden lg:block">

          <div className="flex h-14 w-14 items-center justify-center rounded-full bg-emerald-500 text-slate-950">
            <ArrowRight />
          </div>

        </div>


        <div className="rounded-3xl border border-emerald-500/20 bg-emerald-500/5 p-6">

          <div className="flex items-center gap-3">

            <BrainCircuit className="text-emerald-400" />

            <h3 className="font-semibold">
              After GramCast AI
            </h3>

          </div>


          <p className="mt-5 text-sm text-slate-400">
            Panchayat-Level Intelligence
          </p>


          <div className="mt-5 grid grid-cols-2 gap-3">

            <Result
              name="Panchayat A"
              value="AI Output"
              risk="Low / Moderate"
            />

            <Result
              name="Panchayat B"
              value="AI Output"
              risk="Localized Risk"
            />

            <Result
              name="Panchayat C"
              value="AI Output"
              risk="Localized Risk"
            />

            <Result
              name="Panchayat D"
              value="AI Output"
              risk="Localized Risk"
            />

          </div>


          <p className="mt-5 text-xs leading-5 text-slate-500">
            Actual values are generated by the running
            downscaling model during the live demonstration.
          </p>

        </div>

      </div>

    </section>

  );

}


function Result({
  name,
  value,
  risk,
}: {
  name: string;
  value: string;
  risk: string;
}) {

  return (

    <div className="rounded-xl border border-emerald-500/10 bg-slate-950 p-3">

      <p className="text-xs text-slate-500">
        {name}
      </p>

      <p className="mt-1 font-semibold text-emerald-400">
        {value}
      </p>

      <p className="mt-1 text-[11px] text-slate-600">
        {risk}
      </p>

    </div>

  );

}
